<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KlasifikasiArsipSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();
        $db->table('klasifikasi_arsip')->truncate();
        $data = [
            ['kode' => 'PR', 'kode_induk' => null, 'uraian' => 'Perencanaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS', 'kode_induk' => null, 'uraian' => 'Peningkatan Kesejahteraan Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.01', 'kode_induk' => "PR", 'uraian' => 'Pokok Kebijakan dan Strategis Pembangunan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.01', 'kode_induk' => "KS", 'uraian' => 'Peningkatan Kesejahteraan Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.01.00', 'kode_induk' => "PR.01", 'uraian' => 'Rencana Pembangunan Jangka Panjang (RPJP)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.02', 'kode_induk' => "KS", 'uraian' => 'Penanganan Kemiskinan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.01.01', 'kode_induk' => "PR.01", 'uraian' => 'Rencana Pembangunan Jangaka Menengah (RPJM)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.02.00', 'kode_induk' => "KS.02", 'uraian' => 'SInkronisasi Data Kemiskinan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.01.02', 'kode_induk' => "PR.01", 'uraian' => 'Rencana Kerja Pemerintah (RKP)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.02.01', 'kode_induk' => "KS.02", 'uraian' => 'Penanganan Kemiskinan Perkotaan dan Pedesaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.01.03', 'kode_induk' => "PR.01", 'uraian' => 'Musyawarah Perencanaan Pembangunan Nasional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.03', 'kode_induk' => "KS", 'uraian' => 'Jaminan Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.02', 'kode_induk' => "PR", 'uraian' => 'Program Kerja Tahunan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.03.00', 'kode_induk' => "KS.03", 'uraian' => 'Asistensi Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.02.00', 'kode_induk' => "PR.02", 'uraian' => 'Usulan Unit Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.03.01', 'kode_induk' => "KS.03", 'uraian' => 'Asuransi Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.02.01', 'kode_induk' => "PR.02", 'uraian' => 'Program Kerja Tahunan Unit Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.04', 'kode_induk' => "KS", 'uraian' => 'Bantuan Subsidi Tepat Sasaran', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.02.02', 'kode_induk' => "PR.02", 'uraian' => 'Program Kerja Tahunan Lembaga/Instansi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.04.00', 'kode_induk' => "KS.04", 'uraian' => 'Bantuan Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.03', 'kode_induk' => "PR", 'uraian' => 'Penetapan Kinerja (PK/TAPJA)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.04.01', 'kode_induk' => "KS.04", 'uraian' => 'Subsidi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.04', 'kode_induk' => "PR", 'uraian' => 'Perencanaan Penyusunan Rencana Anggaran dan Penyusunan Renstra', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.05', 'kode_induk' => "KS", 'uraian' => 'Pemberdayaan Disabilitas dan Lanjut Usia', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.04.00', 'kode_induk' => "PR.04", 'uraian' => 'Penyusunan Rencana Anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.05.00', 'kode_induk' => "KS.05", 'uraian' => 'Pemberdayaan Disabilitas', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.04.01', 'kode_induk' => "PR.04", 'uraian' => 'Penyusunan Renstra', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KS.05.01', 'kode_induk' => "KS.05", 'uraian' => 'Pemberdayaan Lanjut Usia', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.05', 'kode_induk' => "PR", 'uraian' => 'Revisi Anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB', 'kode_induk' => null, 'uraian' => 'Pemerataan Pembangunan Wilayah dan Penanggulangan Bencana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.05.00', 'kode_induk' => "PR.05", 'uraian' => 'Daftar Isian Pelaksanaan Anggaran dan Petunjuk Operasional Kegiatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.01', 'kode_induk' => "WB", 'uraian' => 'Pemerataan Pembangunan Wilayah dan Penanggulangan Bencana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.05.01', 'kode_induk' => "PR.05", 'uraian' => 'Anggaran Biaya Tambahan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.02', 'kode_induk' => "WB", 'uraian' => 'Pemerataan Pembangunan WIlayah', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.05.02', 'kode_induk' => "PR.05", 'uraian' => 'Anggaran Pendapatan dan Belanja Negara Perubahan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.02.00', 'kode_induk' => "WB.02", 'uraian' => 'Pengembangan Sarana dan Prasarana Kawasan tertinggal', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.06', 'kode_induk' => "PR", 'uraian' => 'Laporan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.02.01', 'kode_induk' => "WB.02", 'uraian' => 'Pengembangan Kemitraan dan Kelembagaan Kwasan Berkembang', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.06.00', 'kode_induk' => "PR.06", 'uraian' => 'Laporan Berkala', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.03', 'kode_induk' => "WB", 'uraian' => 'Pemberdayaan Kawasan dan Mobilitas Spasial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.06.01', 'kode_induk' => "PR.06", 'uraian' => 'Laporan Akuntabilitas Kinerja Instansi Pemerintah', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.03.00', 'kode_induk' => "WB.03", 'uraian' => 'Pemberdayaan Kawasan Strategis', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.06.02', 'kode_induk' => "PR.06", 'uraian' => 'Laporan Insedental', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.03.01', 'kode_induk' => "WB.03", 'uraian' => 'Pengembangan Karyawan Khusus', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.07', 'kode_induk' => "PR", 'uraian' => 'Evaluasi Program', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.03.02', 'kode_induk' => "WB.03", 'uraian' => 'Bhakti PMK', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.07.00', 'kode_induk' => "PR.07", 'uraian' => 'Program Unit Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.03.03', 'kode_induk' => "WB.03", 'uraian' => 'Pengembangan Sarana dan Prasarana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.07.01', 'kode_induk' => "PR.07", 'uraian' => 'Program Kementerian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.03.04', 'kode_induk' => "WB.03", 'uraian' => 'Pengelolaan Sumber Daya', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.08', 'kode_induk' => "PR", 'uraian' => 'Reformasi Birokrasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.04', 'kode_induk' => "WB", 'uraian' => 'Mitigasi Bencana dan Konflik SOsial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.08.00', 'kode_induk' => "PR.08", 'uraian' => 'Pelaksanaan Program Reformasi Birokrasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.04.00', 'kode_induk' => "WB.04", 'uraian' => 'Mitigasi Bencana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PR.08.01', 'kode_induk' => "PR.08", 'uraian' => 'Penilaian Mandiri Pelaksanaan Reformasi Birokrasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.04.01', 'kode_induk' => "WB.04", 'uraian' => 'Penganganan Pengungsi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL', 'kode_induk' => null, 'uraian' => 'Kerjasama Lembaga', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.04.02', 'kode_induk' => "WB.04", 'uraian' => 'Bantuan Darurat', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL.01', 'kode_induk' => "KL", 'uraian' => 'Rancangan Kebijakan terkait Pengelolaan Kegiatan Strategis', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.04.03', 'kode_induk' => "WB.04", 'uraian' => 'Pencegahan Konflik Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL.02', 'kode_induk' => "KL", 'uraian' => 'Kerjasama Dalam Negeri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.04.04', 'kode_induk' => "WB.04", 'uraian' => 'Pemulihan Pasca Konflik Sosial', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL.03', 'kode_induk' => "KL", 'uraian' => 'Kerjasama Luar Negeri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.05', 'kode_induk' => "WB", 'uraian' => 'Kedaruratan dan Manajemen Pasca Bencana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL.03.00', 'kode_induk' => "KL.03", 'uraian' => 'Nota Kesepahaman/Memorandum of Understanding/Kontrak/ Perjanjian Kerjasama Regional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.05.00', 'kode_induk' => "WB.05", 'uraian' => 'Kedaruratan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL.03.01', 'kode_induk' => "KL.03", 'uraian' => 'Nota Kesepahaman/Memorandum of Understanding/Kontrak/ Perjanjian Kerjasama Multilateral', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.05.01', 'kode_induk' => "WB.05", 'uraian' => 'Pemulihan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KL.03.02', 'kode_induk' => "KL.03", 'uraian' => 'Nota Kesepahaman/Memorandum of Understanding/Kontrak/ Perjanjian Kerjasama Bilateral', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'WB.05.02', 'kode_induk' => "WB.05", 'uraian' => 'Pemberdayaan Masyarakat', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK', 'kode_induk' => null, 'uraian' => 'Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK', 'kode_induk' => null, 'uraian' => 'Peningkatan Kualitas Kesehatan dan Pembangunan Kependudukan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.01', 'kode_induk' => "HK", 'uraian' => 'Program legislasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.01', 'kode_induk' => "KK", 'uraian' => 'Peningkatan Kualitas Kesehatan dan Pembangunan Kependudukan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.02', 'kode_induk' => "HK", 'uraian' => 'Produk Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.02', 'kode_induk' => "KK", 'uraian' => 'Ketahanan Gizi dan Promosi Kesehatan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.02.00', 'kode_induk' => "HK.02", 'uraian' => 'Produk Hukum yang bersifat pengaturan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.02.00', 'kode_induk' => "KK.02", 'uraian' => 'Ketahanan Gizi dan Kesehatan Ibu dan Anak', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.02.01', 'kode_induk' => "HK.02", 'uraian' => 'Produk Hukum yang bersifat penetapan (beschiking)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.02.01', 'kode_induk' => "KK.02", 'uraian' => 'Promosi Kesehatan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.03', 'kode_induk' => "HK", 'uraian' => 'Dokumen Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.03', 'kode_induk' => "KK", 'uraian' => 'Pengendalian Penanggulangan Penyakit', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.04', 'kode_induk' => "HK", 'uraian' => 'Sosialisasi/Penyuluhan/Pembinaan Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.03.00', 'kode_induk' => "KK.03", 'uraian' => 'Pengendalian Penyakit', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.04.00', 'kode_induk' => "HK.04", 'uraian' => 'Sosialisasi/Penyuluhan/Pembinaan Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.03.01', 'kode_induk' => "KK.03", 'uraian' => 'Penanggulangan KLB/Wabah dan Daruratan Kesehatan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.04.01', 'kode_induk' => "HK.04", 'uraian' => 'Laporan Hasil Pelaksanaan Sosialiasi/Penyuluhan/Pembinaan Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.04', 'kode_induk' => "KK", 'uraian' => 'Pelayanan Kesehatan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.05', 'kode_induk' => "HK", 'uraian' => 'Kasus/Sengketa Hukum', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.04.00', 'kode_induk' => "KK.04", 'uraian' => 'Pelayanan Dasar dan Rujukan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.05.00', 'kode_induk' => "HK.05", 'uraian' => 'Litigasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.04.01', 'kode_induk' => "KK.04", 'uraian' => 'Pembiayaan Kesehatan dan Farmasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HK.05.01', 'kode_induk' => "HK.05", 'uraian' => 'Non Litigasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.05', 'kode_induk' => "KK", 'uraian' => 'Kependudukan dan Keluarga berencana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT', 'kode_induk' => null, 'uraian' => 'Organisasi dan Ketatalaksanaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.05.00', 'kode_induk' => "KK.05", 'uraian' => 'Pembangunan Kependudukan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT.01', 'kode_induk' => "OT", 'uraian' => 'Organisasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KK.05.01', 'kode_induk' => "KK.05", 'uraian' => 'Keluarga Berencana', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT.01.00', 'kode_induk' => "OT.01", 'uraian' => 'Struktur/Tugas/Fungsi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP', 'kode_induk' => null, 'uraian' => 'Peningkatan Kualitas Anak, Perempuan, dan Pemuda', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT.01.01', 'kode_induk' => "OT.01", 'uraian' => 'Evaluasi Organisasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.01', 'kode_induk' => "AP", 'uraian' => 'Peningkatan Kualitas Anak, Perempuan, dan Pemuda', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT.02', 'kode_induk' => "OT", 'uraian' => 'Ketatalaksanaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.02', 'kode_induk' => "AP", 'uraian' => 'Pemenuhan Hak dan Perlindungan Anak', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT.02.00', 'kode_induk' => "OT.02", 'uraian' => 'Penetapan/Penyelarasan Standar Operasional Prosedur', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.02.00', 'kode_induk' => "AP.02", 'uraian' => 'Pemenuhan Hak Anak', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'OT.02.01', 'kode_induk' => "OT.02", 'uraian' => 'Tata Hubungan Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.02.01', 'kode_induk' => "AP.02", 'uraian' => 'Perlindungan Anak', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS', 'kode_induk' => null, 'uraian' => 'Persidangan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.03', 'kode_induk' => "AP", 'uraian' => 'Pemenuhan Hak, Perlindungan, dan Pemberdayaan Perempuan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.01', 'kode_induk' => "PS", 'uraian' => 'Rapat Koordinasi Tingkat Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.03.00', 'kode_induk' => "AP.03", 'uraian' => 'Pemenuhan Hak Perempuan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'AP.03.01', 'kode_induk' => "AP.03", 'uraian' => 'Perlindungan Perempuan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.01.00', 'kode_induk' => "PS.01", 'uraian' => 'Rapat Koordinasi Tingkat Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PS.01.01', 'kode_induk' => "PS.01", 'uraian' => 'Rapat Terbatas (Ratas)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.03.02', 'kode_induk' => "AP.03", 'uraian' => 'Pemberdayaan Bidang Ekonomi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.01.02', 'kode_induk' => "PS.01", 'uraian' => 'Rapat Paripurna Tingkat Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.03.03', 'kode_induk' => "AP.03", 'uraian' => 'Pemberdayaan Bidang Sosial Budaya', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.01.03', 'kode_induk' => "PS.01", 'uraian' => 'Rapat Koordinasi (Rakor) Tingkat Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.04', 'kode_induk' => "AP", 'uraian' => 'Pemberdayaan Pemuda', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.01.04', 'kode_induk' => "PS.01", 'uraian' => 'Rapat Menteri dengan Dewan Perwakilan Rakyat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.04.00', 'kode_induk' => "AP.04", 'uraian' => 'Pemberdayaan Pemuda', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.02', 'kode_induk' => "PS", 'uraian' => 'Rapat Koordinasi Tingkat Pimpinan Tinggi Madya', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.04.01', 'kode_induk' => "AP.04", 'uraian' => 'Pengembangan Pemuda', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.03', 'kode_induk' => "PS", 'uraian' => 'Rapat Internal Staf', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.05', 'kode_induk' => "AP", 'uraian' => 'Ketahanan dan Kesejahteraan Keluarga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.03.00', 'kode_induk' => "PS.03", 'uraian' => 'Rapat Internal Staf Pimpinan Menteri Koordinator Bidang PMK', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.05.00', 'kode_induk' => "AP.05", 'uraian' => 'Ketahanan Keluarga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.03.01', 'kode_induk' => "PS.03", 'uraian' => 'Rapat Intenal Staf Pimpinan Sekretaris Kementerian Koordinator Bidang PMK', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'AP.05.01', 'kode_induk' => "AP.05", 'uraian' => 'Peningkatan Kesejahteraan Keluarga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.04', 'kode_induk' => "PS", 'uraian' => 'Pengelolaan Data', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK', 'kode_induk' => null, 'uraian' => 'Revolusi Mental, Pemajuan Kebudayaan, dan Prestasi Olahraga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PS.04.00', 'kode_induk' => "PS.04", 'uraian' => 'Pengelolaan Data di Tingkat Pusat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.01', 'kode_induk' => "RK", 'uraian' => 'Revolusi Mental, Pemajuan Kebudayaan, dan Prestasi Bangsa', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM', 'kode_induk' => null, 'uraian' => 'Hubungan Masyarakat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.02', 'kode_induk' => "RK", 'uraian' => 'Revolusi Mental', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01', 'kode_induk' => "HM", 'uraian' => 'Hubungan Antar Lembaga dan Masyarakat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.02.00', 'kode_induk' => "RK.02", 'uraian' => 'Revolusi Mental', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.00', 'kode_induk' => "HM.01", 'uraian' => 'Dewan Perwakilan Rakyat/Dewan Perwakilan Daerah/Majelis Permusyawaratan Rakyat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.02.01', 'kode_induk' => "RK.02", 'uraian' => 'Koordinasi dan Monitoring Evaluasi Gerakan Revolusi Mental', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.01', 'kode_induk' => "HM.01", 'uraian' => 'Lembaga Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.03', 'kode_induk' => "RK", 'uraian' => 'Pemajuan dan Pelestarian Kebudayaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.02', 'kode_induk' => "HM.01", 'uraian' => 'Organisasi Nasional dan Internasional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.03.00', 'kode_induk' => "RK.03", 'uraian' => 'Cagar Budaya dan Permuseuman', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.03', 'kode_induk' => "HM.01", 'uraian' => 'Perusahaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.03.01', 'kode_induk' => "RK.03", 'uraian' => 'Sejarah dan Warisan Dunia', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.04', 'kode_induk' => "HM.01", 'uraian' => 'Perguruan Tinggi/Sekolah', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.04', 'kode_induk' => "RK", 'uraian' => 'Peningkatan Prestasi Olahraga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.05', 'kode_induk' => "HM.01", 'uraian' => 'Media Massa', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.04.00', 'kode_induk' => "RK.04", 'uraian' => 'Prestasi Olahraga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.01.06', 'kode_induk' => "HM.01", 'uraian' => 'Forum Kehumasan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.04.01', 'kode_induk' => "RK.04", 'uraian' => 'Pembudayaan Olahraga', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.02', 'kode_induk' => "HM", 'uraian' => 'Pemenuhan Informasi Publik', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.05', 'kode_induk' => "RK", 'uraian' => 'Literasi, Inovasi, dan Kreativitas', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.03', 'kode_induk' => "HM", 'uraian' => 'Penerbitan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.05.00', 'kode_induk' => "RK.05", 'uraian' => 'Nilai Budaya dan Karakter Bangsa', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.04', 'kode_induk' => "HM", 'uraian' => 'Publikasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RK.05.01', 'kode_induk' => "RK.05", 'uraian' => 'Industri Budaya', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.05', 'kode_induk' => "HM", 'uraian' => 'Dokumentasi/Liputan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB', 'kode_induk' => null, 'uraian' => 'Peningkatan Kualitas Pendidikan dan Moderasi Beragama', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.06', 'kode_induk' => "HM", 'uraian' => 'Pengumpulan, Pengolahan dan Penyajian Informasi Kelembagaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.01', 'kode_induk' => "PB", 'uraian' => 'Peningkatan Kualitas Pendidikan dan Moderasi Beragama', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.07', 'kode_induk' => "HM", 'uraian' => 'Penghargaan Kelembagaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.02', 'kode_induk' => "PB", 'uraian' => 'Pendidikan Anak Usia Dini, Dasar dan Menengah', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'HM.08', 'kode_induk' => "HM", 'uraian' => 'Pameran/Sayembara/Lomba,Festival,Pembuatan Spanduk dan Iklan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.02.00', 'kode_induk' => "PB.02", 'uraian' => 'PAUD dan Pendidikan Masyarakat', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KE', 'kode_induk' => null, 'uraian' => 'Kepustakaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.02.01', 'kode_induk' => "PB.02", 'uraian' => 'Pendidikan Dasar', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'PB.02.02', 'kode_induk' => "PB.02", 'uraian' => 'Pendidikan Menengah', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KE.01', 'kode_induk' => "KE", 'uraian' => 'Deposit Bahan Pustaka', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KE.01.00', 'kode_induk' => "KE.01", 'uraian' => 'Bukti Penerimaan Koleksi Bahan Pustaka Deposit', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.02.03', 'kode_induk' => "PB.02", 'uraian' => 'Pendidikan Keterampilan Bekerja', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KE.01.01', 'kode_induk' => "KE.01", 'uraian' => 'Administrasi Pengolahan Deposit Bahan Pustaka', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.03', 'kode_induk' => "PB", 'uraian' => 'Pendidikan Vokasi dan Pendidikan Tinggi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KE.02', 'kode_induk' => "KE", 'uraian' => 'Pengadaan dan Pengolahan Bahan Pustaka', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.03.00', 'kode_induk' => "PB.03", 'uraian' => 'Pendidikan Vokasi dan Pendidikan Tinggi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KE.02.00', 'kode_induk' => "KE.02", 'uraian' => 'Pengadaan dan Pengeolahan Bahan Pustaka', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.03.01', 'kode_induk' => "PB.03", 'uraian' => 'Pemanfaatan Ilmu Pengetahuan Teknologi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KE.02.01', 'kode_induk' => "KE.02", 'uraian' => 'Layanan Jasa Perpustakaan dan Informasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.04', 'kode_induk' => "PB", 'uraian' => 'Pendidikan Keagamaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI', 'kode_induk' => null, 'uraian' => 'Teknologi Informasi dan Komunikasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.04.00', 'kode_induk' => "PB.04", 'uraian' => 'Pembinaan Umat Beragama', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.01', 'kode_induk' => "TI", 'uraian' => 'Rencana Strategis/Master plan Pembangunan Sistem Informasin Sistem Informasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.04.01', 'kode_induk' => "PB.04", 'uraian' => 'Pendidikan Agama dan Pendidikan Keagamaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.02', 'kode_induk' => "TI", 'uraian' => 'Dokumentasi Arsitektur', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.05', 'kode_induk' => "PB", 'uraian' => 'Moderasi Beragama', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.03', 'kode_induk' => "TI", 'uraian' => 'Dokumen Implementasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.05.00', 'kode_induk' => "PB.05", 'uraian' => 'Pemberdayaan Umat Beragama', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.04', 'kode_induk' => "TI", 'uraian' => 'Perekaman dan Pemutakhiran Data', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.05.01', 'kode_induk' => "PB.05", 'uraian' => 'Kerukunan Umat Beragama', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.05', 'kode_induk' => "TI", 'uraian' => 'Migrasi Sistem Aplikasi dan Data', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.06', 'kode_induk' => "PB", 'uraian' => 'Pendidikan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.06', 'kode_induk' => "TI", 'uraian' => 'Dokumen Hosting', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PB.07', 'kode_induk' => "PB", 'uraian' => 'Keagamaan dan Hari Besar', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'TI.07', 'kode_induk' => "TI", 'uraian' => 'Keamanan Data', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PM', 'kode_induk' => null, 'uraian' => 'Pembangunan Manusia dan Kebudayaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP', 'kode_induk' => null, 'uraian' => 'Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PM.01', 'kode_induk' => "PM", 'uraian' => 'Perumusan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.01', 'kode_induk' => "KP", 'uraian' => 'Formasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PM.01.00', 'kode_induk' => "PM.01", 'uraian' => 'Koordinasi dan Sinkronisasi tentang Pembangunan Manusia dan Kebudayaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.01.00', 'kode_induk' => "KP.01", 'uraian' => 'Bahan Kebutuhan dan Pertimbangan Formasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PM.01.01', 'kode_induk' => "PM.01", 'uraian' => 'Pelaksanaan Kebijakan Terkait Pembangunan Manusia dan Kebudayaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.01.01', 'kode_induk' => "KP.01", 'uraian' => 'Usulan dan pertimbangan Formasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PM.01.02', 'kode_induk' => "PM.01", 'uraian' => 'Sosialisasi tentang Pembangunan Manusia dan Kebudayaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.01.02', 'kode_induk' => "KP.01", 'uraian' => 'Persetujuan Formasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PM.01.03', 'kode_induk' => "PM.01", 'uraian' => 'Monitoring dan Evaluasi terkait Pembangunan Manusia dan Kebudayaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.01.03', 'kode_induk' => "KP.01", 'uraian' => 'Penetapan Formasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP', 'kode_induk' => null, 'uraian' => 'Pengkajian dan Penelaahan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.02', 'kode_induk' => "KP", 'uraian' => 'Pengadaan Aparatur Sipil Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.01', 'kode_induk' => "PP", 'uraian' => 'Politik, Hukum, Keamanan, Pemerintahan, dan Hak Asasi Manusia', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.03', 'kode_induk' => "KP", 'uraian' => 'Penetapan Nomor Induk Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.01.00', 'kode_induk' => "PP.01", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.04', 'kode_induk' => "KP", 'uraian' => 'Penetapan Penyedia Jasa peroangan/Pegawai Pemerintah dengan Perjanjian Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.01.01', 'kode_induk' => "PP.01", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.05', 'kode_induk' => "KP", 'uraian' => 'Pengangkatan dan Pemberhentian dalam Jabatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.01.02', 'kode_induk' => "PP.01", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.05.00', 'kode_induk' => "KP.05", 'uraian' => 'Struktural', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.01.03', 'kode_induk' => "PP.01", 'uraian' => 'Monitoring dan Evaluasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.05.01', 'kode_induk' => "KP.05", 'uraian' => 'Fungsional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.02', 'kode_induk' => "PP", 'uraian' => 'Multikularisme, Restorasi Sosail, dan Jati Diri Bangsa', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.05.02', 'kode_induk' => "KP.05", 'uraian' => 'Pendelegasian Wewenang', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.02.00', 'kode_induk' => "PP.02", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.06', 'kode_induk' => "KP", 'uraian' => 'Mutasi Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.02.01', 'kode_induk' => "PP.02", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.06.00', 'kode_induk' => "KP.06", 'uraian' => 'Mutasi Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.02.02', 'kode_induk' => "PP.02", 'uraian' => 'Sosialisasi Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.06.01', 'kode_induk' => "KP.06", 'uraian' => 'Kenaikan Pangkat/Golongan Jabatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.02.03', 'kode_induk' => "PP.02", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.06.02', 'kode_induk' => "KP.06", 'uraian' => 'Penetapan Perubahan Data Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.02.04', 'kode_induk' => "PP.02", 'uraian' => 'Monitoring dan Evaluasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.06.03', 'kode_induk' => "KP.06", 'uraian' => 'Peninjauan Masa Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.03', 'kode_induk' => "PP", 'uraian' => 'Sumber Daya Ekonomi, Usaha Mikro, Kecil, dan Menengah, Ekonomi Kreatif, dan Ketenagakerjaan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.06.04', 'kode_induk' => "KP.06", 'uraian' => 'Berkas Badan Pertimbangan Jabatan dan Pangkat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.03.00', 'kode_induk' => "PP.03", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.07', 'kode_induk' => "KP", 'uraian' => 'Pengembangan Karir', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.03.01', 'kode_induk' => "PP.03", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.07.00', 'kode_induk' => "KP.07", 'uraian' => 'Pelatihan Dasar', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.03.02', 'kode_induk' => "PP.03", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.07.01', 'kode_induk' => "KP.07", 'uraian' => 'Pendidikan dan Pelatihan Pimpinan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.03.03', 'kode_induk' => "PP.03", 'uraian' => 'Monitoring dan Evaluasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.07.02', 'kode_induk' => "KP.07", 'uraian' => 'Pendidikan dan Pelatihan Teknis', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.04', 'kode_induk' => "PP", 'uraian' => 'Sumber Daya Kemaritiman', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.07.03', 'kode_induk' => "KP.07", 'uraian' => 'Pendidikan dan Pelatihan Lembaga Ketahanan Nasional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.04.00', 'kode_induk' => "PP.04", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.08', 'kode_induk' => "KP", 'uraian' => 'Tugas Belajar/Ijin Belajar/Kursus/Magang/Ujian Dinas/Praktek/Kerja di Instansi Lain/Pertukaran ASN', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.04.01', 'kode_induk' => "PP.04", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.08.00', 'kode_induk' => "KP.08", 'uraian' => 'Perencanaan dan Penyusunan Analisis Kebutuhan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.04.02', 'kode_induk' => "PP.04", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.08.01', 'kode_induk' => "KP.08", 'uraian' => 'Laporan atas Kegiatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.04.03', 'kode_induk' => "PP.04", 'uraian' => 'Monitoring dan Evaluasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.08.02', 'kode_induk' => "KP.08", 'uraian' => 'Ijazah/Surat Tanda Tamat Pendidikan dan Pelatihan/Sertifikat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.05', 'kode_induk' => "PP", 'uraian' => 'Sustainable Development', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.09', 'kode_induk' => "KP", 'uraian' => 'Penyesuaian Ijazah', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.05.00', 'kode_induk' => "PP.05", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.10', 'kode_induk' => "KP", 'uraian' => 'Penyusunan Sistem Karir', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.05.01', 'kode_induk' => "PP.05", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.11', 'kode_induk' => "KP", 'uraian' => 'Angka Kredit', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.05.02', 'kode_induk' => "PP.05", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.12', 'kode_induk' => "KP", 'uraian' => 'Kinerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.05.03', 'kode_induk' => "PP.05", 'uraian' => 'Monitoring dan Evaluasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.12.00', 'kode_induk' => "KP.12", 'uraian' => 'Penilaian Kinerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.06', 'kode_induk' => "PP", 'uraian' => 'Kependudukan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.12.01', 'kode_induk' => "KP.12", 'uraian' => 'Standar Kinerja Pegawai dan Penilaian Prestasi Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.06.00', 'kode_induk' => "PP.06", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.12.02', 'kode_induk' => "KP.12", 'uraian' => 'Pengelolaan Database dan Analisis Sistem Informasi Kinerja Pegawai Aparatur Sipil Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.06.01', 'kode_induk' => "PP.06", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.13', 'kode_induk' => "KP", 'uraian' => 'Kode Etik', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.06.02', 'kode_induk' => "PP.06", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.13.00', 'kode_induk' => "KP.13", 'uraian' => 'Kode Etik Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.06.03', 'kode_induk' => "PP.06", 'uraian' => 'Monitoring dan Evaluasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.13.01', 'kode_induk' => "KP.13", 'uraian' => 'Disiplin', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.07', 'kode_induk' => "PP", 'uraian' => 'Pembangunan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.13.02', 'kode_induk' => "KP.13", 'uraian' => 'Pemberhentian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.07.00', 'kode_induk' => "PP.07", 'uraian' => 'Koordinasi dan Sinkronisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.13.03', 'kode_induk' => "KP.13", 'uraian' => 'Pensiun', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.07.01', 'kode_induk' => "PP.07", 'uraian' => 'Pelaksanaan Kebijakan', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.14', 'kode_induk' => "KP", 'uraian' => 'Status dan Kedudukan Pegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PP.07.02', 'kode_induk' => "PP.07", 'uraian' => 'Sosialisasi', 'fungsi' => 'substantif', 'is_active' => 1],
            ['kode' => 'KP.14.00', 'kode_induk' => "KP.14", 'uraian' => 'Pertimbangan Status Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.14.01', 'kode_induk' => "KP.14", 'uraian' => 'Pertimbangan Kedudukan Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.14.02', 'kode_induk' => "KP.14", 'uraian' => 'Penyelesaian pengelolaan keberatan pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.14.03', 'kode_induk' => "KP.14", 'uraian' => 'Perselisihan/Sengketa Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.15', 'kode_induk' => "KP", 'uraian' => 'Sistem Informasi Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.15.00', 'kode_induk' => "KP.15", 'uraian' => 'Pegolahan Data', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.15.01', 'kode_induk' => "KP.15", 'uraian' => 'Informasi Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.15.02', 'kode_induk' => "KP.15", 'uraian' => 'Pengembangan Sistem Informasi Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.15.03', 'kode_induk' => "KP.15", 'uraian' => 'Pengembangan Sistem Arsip Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16', 'kode_induk' => "KP", 'uraian' => 'Adminsitrasi Kepegawaian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16.00', 'kode_induk' => "KP.16", 'uraian' => 'Surat Pernyataan Melaksanakan Tugas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16.01', 'kode_induk' => "KP.16", 'uraian' => 'Cuti sakit, Cuti Bersalin, Cuti Tahunan, Cuti Alasan Penting', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16.02', 'kode_induk' => "KP.16", 'uraian' => 'Cuti Besar dan Cuti Diluar Tanggungan Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16.03', 'kode_induk' => "KP.16", 'uraian' => 'Dokumentasi Identitas Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16.04', 'kode_induk' => "KP.16", 'uraian' => 'Berkas Kepegawaian dan Daftar Urut Kepangkatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.16.05', 'kode_induk' => "KP.16", 'uraian' => 'Berkas Pengurusan Kenaikan Gaji Berkala, Mutasi Gaji/Tunjangan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17', 'kode_induk' => "KP", 'uraian' => 'Kesejahteraan Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.00', 'kode_induk' => "KP.17", 'uraian' => 'Layanan Pemeliharaan Kesehatan Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.01', 'kode_induk' => "KP.17", 'uraian' => 'Layanan Asuransi Pegawai/Badan Penyelenggara Jaminan Sosial', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.02', 'kode_induk' => "KP.17", 'uraian' => 'Layanan Tabungan Perumahan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.03', 'kode_induk' => "KP.17", 'uraian' => 'Layanan Bantuan Sosial', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.04', 'kode_induk' => "KP.17", 'uraian' => 'Layanan Pakaian Dinas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.05', 'kode_induk' => "KP.17", 'uraian' => 'Layanan Paegawai yang meninggal karena Dinas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.06', 'kode_induk' => "KP.17", 'uraian' => 'Pemberian Tali Kasih', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.07', 'kode_induk' => "KP.17", 'uraian' => 'Pemberian Piagam Penghargaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.17.08', 'kode_induk' => "KP.17", 'uraian' => 'Organisasi Non Kedinasan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.18', 'kode_induk' => "KP", 'uraian' => 'Administrasi Perorangan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.18.00', 'kode_induk' => "KP.18", 'uraian' => 'Berkas Perseorangan Pegawai Negeri Sipil', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.18.01', 'kode_induk' => "KP.18", 'uraian' => 'Berkas perseorangan Pegawai Pemerintahan dengan Perjanjian Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.18.02', 'kode_induk' => "KP.18", 'uraian' => 'Berkas Perseorangan Aparatur Sipil Negara yang Berjasa/Terlibat dalam peristiwa bersekala Nasional.', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.19', 'kode_induk' => "KP", 'uraian' => 'Berkas Perseorangan Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.20', 'kode_induk' => "KP", 'uraian' => 'Penilaian Kompetensi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.20.00', 'kode_induk' => "KP.20", 'uraian' => 'Penilaian Kompetensi Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.20.01', 'kode_induk' => "KP.20", 'uraian' => 'Penilaian Kompetensi Pejabat Eselon I dan II', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.20.02', 'kode_induk' => "KP.20", 'uraian' => 'Hasil Penilaian Kompetensi Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.20.03', 'kode_induk' => "KP.20", 'uraian' => 'Hasil Penilaian Kompetensi Pejabat Eselon I dan II', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.21', 'kode_induk' => "KP", 'uraian' => 'Analisis Jabatan Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.22', 'kode_induk' => "KP", 'uraian' => 'Analisis Beban Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.23', 'kode_induk' => "KP", 'uraian' => 'Standar Kompetensi Jabatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.23.00', 'kode_induk' => "KP.23", 'uraian' => 'Standar Kompetensi Jabatan Struktural', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KP.23.01', 'kode_induk' => "KP.23", 'uraian' => 'Standar Kompetensi Jabatan Fungsional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA', 'kode_induk' => null, 'uraian' => 'Kearsipan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.01', 'kode_induk' => "KA", 'uraian' => 'Administrasi Persuratan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.01.00', 'kode_induk' => "KA.01", 'uraian' => 'Agenda Surat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.01.01', 'kode_induk' => "KA.01", 'uraian' => 'Lembar Pengantar/Buku Ekspedisi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.01.02', 'kode_induk' => "KA.01", 'uraian' => 'Formulir/Catatan Permintaan dan Layanan Penggandaan Dokumen/ Arsip', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.01.03', 'kode_induk' => "KA.01", 'uraian' => 'Formulir/Catatan Permintaan Penomoran Surat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02', 'kode_induk' => "KA", 'uraian' => 'Pemeliharaan Arsip', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02.00', 'kode_induk' => "KA.02", 'uraian' => 'Pengelolaan Arsip Aktif', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02.01', 'kode_induk' => "KA.02", 'uraian' => 'Pengelolaan Arsip Inaktif', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02.02', 'kode_induk' => "KA.02", 'uraian' => 'Penyimpanan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02.03', 'kode_induk' => "KA.02", 'uraian' => 'Alih Media Arsip', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02.04', 'kode_induk' => "KA.02", 'uraian' => 'Akses Pengguna Arsip', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.02.05', 'kode_induk' => "KA.02", 'uraian' => 'Akses Informasi Publik', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.03', 'kode_induk' => "KA", 'uraian' => 'Arsip Vital', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.04', 'kode_induk' => "KA", 'uraian' => 'Arsip Terjaga', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.05', 'kode_induk' => "KA", 'uraian' => 'Sistem Kearsipan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.06', 'kode_induk' => "KA", 'uraian' => 'Penyusunan Arsip', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.06.00', 'kode_induk' => "KA.06", 'uraian' => 'Pemindahan Arsip Inaktif', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.06.01', 'kode_induk' => "KA.06", 'uraian' => 'Pemusnahan Arsip', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.06.02', 'kode_induk' => "KA.06", 'uraian' => 'Penyerahan Arsip Statis', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.07', 'kode_induk' => "KA", 'uraian' => 'Pembinaan Kearsipan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.07.00', 'kode_induk' => "KA.07", 'uraian' => 'Bimbingan Teknis Kearsipan/Bimbingan Konsultasi Kearsipan/ Sosialiasi Kearsipan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.07.01', 'kode_induk' => "KA.07", 'uraian' => 'Supervisi/Pengawasan Kearsipan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KA.07.02', 'kode_induk' => "KA.07", 'uraian' => 'Monitoring', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU', 'kode_induk' => null, 'uraian' => 'Keuangan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01', 'kode_induk' => "KU", 'uraian' => 'Pelaksanaan Anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01.00', 'kode_induk' => "KU.01", 'uraian' => 'Rencana Anggaran Biaya', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01.01', 'kode_induk' => "KU.01", 'uraian' => 'Penggajian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01.02', 'kode_induk' => "KU.01", 'uraian' => 'Pengeluaran Anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01.03', 'kode_induk' => "KU.01", 'uraian' => 'Belanja Barang Habis Pakai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01.04', 'kode_induk' => "KU.01", 'uraian' => 'Belanja Barang Inventaris/Barang Modal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.01.05', 'kode_induk' => "KU.01", 'uraian' => 'Belanja Jasa', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02', 'kode_induk' => "KU", 'uraian' => 'Pengelolaan Perbendaharaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.00', 'kode_induk' => "KU.02", 'uraian' => 'Perbendaharaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.01', 'kode_induk' => "KU.02", 'uraian' => 'KP4 (Kartu Pengawasan Pembayaran Penghasilan Pegawai)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.02', 'kode_induk' => "KU.02", 'uraian' => 'Buku/Kartu Pengawasan Kredit', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.03', 'kode_induk' => "KU.02", 'uraian' => 'Pajak', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.04', 'kode_induk' => "KU.02", 'uraian' => 'Penerimaan Negara Bukan Pajak', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.05', 'kode_induk' => "KU.02", 'uraian' => 'Pengembalian Belanja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.06', 'kode_induk' => "KU.02", 'uraian' => 'Berita Acara Pemeriksaan Kas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.07', 'kode_induk' => "KU.02", 'uraian' => 'Kartu Pengawasan Pembayaran Penghasilan Pegawai', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.02.08', 'kode_induk' => "KU.02", 'uraian' => 'Pembukuan Anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.03', 'kode_induk' => "KU", 'uraian' => 'Verifikasi Anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.04', 'kode_induk' => "KU", 'uraian' => 'Akutansi dan Pelaporan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.04.00', 'kode_induk' => "KU.04", 'uraian' => 'Laporan Kas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.04.01', 'kode_induk' => "KU.04", 'uraian' => 'Laporan Keuangan Tahunan Unit Kerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.04.02', 'kode_induk' => "KU.04", 'uraian' => 'Laporan Keuangan Tahunan Kementerian', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.05', 'kode_induk' => "KU", 'uraian' => 'Pertanggungjawaban Keuangan Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.05.00', 'kode_induk' => "KU.05", 'uraian' => 'Laporan Hasil Pemeriksaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.05.01', 'kode_induk' => "KU.05", 'uraian' => 'Dokumen Penyelesaian Keuangan Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.06', 'kode_induk' => "KU", 'uraian' => 'Ketatausahaan Keuangan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.06.00', 'kode_induk' => "KU.06", 'uraian' => 'Keterangan Penghasilan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.06.01', 'kode_induk' => "KU.06", 'uraian' => 'SKPP (Surat Keterangan Pemberhentian Pembayaran)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.06.02', 'kode_induk' => "KU.06", 'uraian' => 'Pinjaman', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.06.03', 'kode_induk' => "KU.06", 'uraian' => 'Iuran Keanggotaan Organisasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'KU.07', 'kode_induk' => "KU", 'uraian' => 'Bantuan/Pinajaman Luar Negeri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP', 'kode_induk' => null, 'uraian' => 'Ketatausahaan dan Protokol', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.01', 'kode_induk' => "TP", 'uraian' => 'Administrasi Menteri/Pimpinan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.01.00', 'kode_induk' => "TP.01", 'uraian' => 'Agenda Pimpinan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.01.01', 'kode_induk' => "TP.01", 'uraian' => 'Agenda Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.01.02', 'kode_induk' => "TP.01", 'uraian' => 'Sambutan/Pidato Pejabat Eselon 1', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.01.03', 'kode_induk' => "TP.01", 'uraian' => 'Sambutan/Pidato Menteri', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.01.04', 'kode_induk' => "TP.01", 'uraian' => 'Ucapan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02', 'kode_induk' => "TP", 'uraian' => 'Keprotokolan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02.00', 'kode_induk' => "TP.02", 'uraian' => 'Upacara/Acara Kedinasan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02.01', 'kode_induk' => "TP.02", 'uraian' => 'Buku Tamu', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02.02', 'kode_induk' => "TP.02", 'uraian' => 'Buku Tamu Pejabat Eselon I dan Tokoh Berskala Nasional dan Internasional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02.03', 'kode_induk' => "TP.02", 'uraian' => 'Kartu Tanda Penduduk/Surat Perjalanan Dinas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02.04', 'kode_induk' => "TP.02", 'uraian' => 'Kunjungan Dinas Eksternal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'TP.02.05', 'kode_induk' => "TP.02", 'uraian' => 'Daftar Nama/Alamat Kantor/Pejabat', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT', 'kode_induk' => null, 'uraian' => 'Kerumahtanggaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.01', 'kode_induk' => "RT", 'uraian' => 'Perencanaan Pengadaan Barang dan Jasa', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.01.00', 'kode_induk' => "RT.01", 'uraian' => 'Analisis dan Pengadaan Perlengkapan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.01.01', 'kode_induk' => "RT.01", 'uraian' => 'Tata Ruang', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.01.02', 'kode_induk' => "RT.01", 'uraian' => 'Daftar Perkenalan Mampu', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.02', 'kode_induk' => "RT", 'uraian' => 'Pelaksanaan Pengadaan Barang dan Jasa', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03', 'kode_induk' => "RT", 'uraian' => 'Pengelolaan Barang Milik Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.00', 'kode_induk' => "RT.03", 'uraian' => 'Penyimpanan Barang Milik Negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.01', 'kode_induk' => "RT.03", 'uraian' => 'Distribusi Penyaluran Barang milik negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.02', 'kode_induk' => "RT.03", 'uraian' => 'Inventarisasi barang milik negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.03', 'kode_induk' => "RT.03", 'uraian' => 'Penghapusan barang milik negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.04', 'kode_induk' => "RT.03", 'uraian' => 'Hibah', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.05', 'kode_induk' => "RT.03", 'uraian' => 'Pelaporan barang milik negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.03.06', 'kode_induk' => "RT.03", 'uraian' => 'Sertifikasi barang milik negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.04', 'kode_induk' => "RT", 'uraian' => 'Dokumen kepemilikan aset/kekayaan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.05', 'kode_induk' => "RT", 'uraian' => 'Pemeliharaan/perawatan barang milik negara', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.05.00', 'kode_induk' => "RT.05", 'uraian' => 'Pemeliharaan gedung dan taman', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.05.01', 'kode_induk' => "RT.05", 'uraian' => 'Pengurusan kendaraan dinas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.05.02', 'kode_induk' => "RT.05", 'uraian' => 'Pengelolaan jaringan listrik,air,telpon dan komputer', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.06', 'kode_induk' => "RT", 'uraian' => 'Penggunaan sarana dan prasarana', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.07', 'kode_induk' => "RT", 'uraian' => 'Ketertiban dan keamanan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.07.00', 'kode_induk' => "RT.07", 'uraian' => 'Pengamanan, penjagaan dan pengawalan terhadap pejabat, kantor dan rumah dinas', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'RT.07.01', 'kode_induk' => "RT.07", 'uraian' => 'Laporan ketertiban dan keamanan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA', 'kode_induk' => null, 'uraian' => 'Pengawasan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.01', 'kode_induk' => "PA", 'uraian' => 'Audit', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.01.00', 'kode_induk' => "PA.01", 'uraian' => 'Audit kinerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.01.01', 'kode_induk' => "PA.01", 'uraian' => 'Audit operasional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.01.02', 'kode_induk' => "PA.01", 'uraian' => 'Audit khusus', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.01.03', 'kode_induk' => "PA.01", 'uraian' => 'Audit unsur tindak pindana', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02', 'kode_induk' => "PA", 'uraian' => 'Reviu', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.00', 'kode_induk' => "PA.02", 'uraian' => 'Reviu laporan leuangan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.01', 'kode_induk' => "PA.02", 'uraian' => 'Reviu laporan kinerja', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.02', 'kode_induk' => "PA.02", 'uraian' => 'Reviu rencana anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.03', 'kode_induk' => "PA.02", 'uraian' => 'Reviu revisi anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.04', 'kode_induk' => "PA.02", 'uraian' => 'Reviu pengelolaan anggaran', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.05', 'kode_induk' => "PA.02", 'uraian' => 'Reviu rencana kegiatan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.06', 'kode_induk' => "PA.02", 'uraian' => 'Reviu pengendalian internal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.02.07', 'kode_induk' => "PA.02", 'uraian' => 'Reviu lainnya', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.03', 'kode_induk' => "PA", 'uraian' => 'Evaluasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.03.00', 'kode_induk' => "PA.03", 'uraian' => 'Evaluasi sistem akuntabilitas kinerja instansi pemerintah (SAKIP)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.03.01', 'kode_induk' => "PA.03", 'uraian' => 'Evaluasi reformasi birokrasi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.03.02', 'kode_induk' => "PA.03", 'uraian' => 'Evaluasi lainnya', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.04', 'kode_induk' => "PA", 'uraian' => 'Pemantauan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.04.00', 'kode_induk' => "PA.04", 'uraian' => 'Pemantauan rekomendasi audit internal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.04.01', 'kode_induk' => "PA.04", 'uraian' => 'Pemantauan rekomendasi audit eksternal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.04.02', 'kode_induk' => "PA.04", 'uraian' => 'Tuntutan ganti rugi (TGR)', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.04.03', 'kode_induk' => "PA.04", 'uraian' => 'Pemantauan unsur tindak pidana korupsi', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.05', 'kode_induk' => "PA", 'uraian' => 'Pengaduan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.05.00', 'kode_induk' => "PA.05", 'uraian' => 'Pengaduan Internal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.05.01', 'kode_induk' => "PA.05", 'uraian' => 'Pengaduan Ekstenal', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06', 'kode_induk' => "PA", 'uraian' => 'Pengawasan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.00', 'kode_induk' => "PA.06", 'uraian' => 'Rencana strategi pengawasan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.01', 'kode_induk' => "PA.06", 'uraian' => 'Rencana kerja tahunan', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.02', 'kode_induk' => "PA.06", 'uraian' => 'Rapat koordinasi pengawasan tingkat nasional', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.03', 'kode_induk' => "PA.06", 'uraian' => 'Laporan hasil audit', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.04', 'kode_induk' => "PA.06", 'uraian' => 'Laporan hasil reviu', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.05', 'kode_induk' => "PA.06", 'uraian' => 'Laporan pengembangan aparat pengendalian intern pemerintah', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.06', 'kode_induk' => "PA.06", 'uraian' => 'Laporan pelaksanaan sistem pengendalian intern pemerintah', 'fungsi' => 'fasilitatif', 'is_active' => 1],
            ['kode' => 'PA.06.07', 'kode_induk' => "PA.06", 'uraian' => 'Laporan kegiatan pengawasan lainnya', 'fungsi' => 'fasilitatif', 'is_active' => 1],
        ];
        $db->table('klasifikasi_arsip')->insertBatch($data);
        echo 'Seeder selesai: ' . count($data) . ' kode diimpor.' . PHP_EOL;
    }
}
